== The @ErrorsHandler Annotation

The @ErrorsHandler annotation injects a call to the default error handling method, which is injected by the plugin.
The annotation can either be applied to the controller class itself or to individual actions. If
the annotation is applied at the class level it will be injected to each action, however applying it at the
action level will override the class level behavior. The annotation can also be passed an optional name of an alternate method to call. The error handling functionality will not be applied to private methods or methods annotated with @SkipErrorsHandler.

If you use parameters outside of a command object, and those parameters have binding errors, those will be included in the
list sent to the error handler, but for each parameter you will have to include an entry in your i18n message bundle. For example:
----
params.<Your parameter name here>.conversion.error = Your error massage for <Your parameter name> had an error binding.
----

===== Example Usage:
[source,groovy]
----
    package test.command

    import com.virtualdogbert.ast.ErrorsHandler
    import grails.converters.JSON
    
    @ErrorsHandler
    class TestController {

        def index(TestCommand test) {
            //some controller code
        }

        @ErrorsHandler(handler = 'someOtherErrorHandler') //over rides the default.
        def list(TestCommand test) {
            //some controller code
        }

        @SkipErrorsHandler //Skips the error handler injection from the class annotation.
        def list(TestCommand test) {
            //some controller code
        }

        //Your error handler
        private boolean someOtherErrorHandler(List commandObjects) {
            List errors = commandObjects.inject([]) { result, commandObject ->

                if (commandObject.hasErrors()) {
                    result + (commandObject.errors as JSON)
                } else {
                    result
                }

            } as List

            if (errors) {
                //Do something
                return true
            }
            //possibly do something else
            return false
        }
    }
----


===== Code injected by the transformation into the affected actions:
[source,groovy]
----
    if(errorsHandler( [<every commandObject in the actions parameter list>] )){ return null }
----

===== Default error handler injected into all controllers:
[source,groovy]
----
    boolean errorsHandler(List commandObjects) {
        List errors = commandObjects.inject([]) { result, commandObject ->

            if (commandObject.hasErrors()) {
                result + (commandObject.errors as JSON)
            } else {
                result
            }

        } as List

        if (errors) {
            render errors
            return true
        }

        return false
    }
----

