== Version History
* 3.0.2
** Fixing the default error handler for the audo binding in 3.0.0 to do a validate rather than checking hasErrors.
* 3.0.0/3.0.1
** Added auto binding for url parameters to command objects, when using the default error handler.
since this can break non default error handlers I bumped the version to 3.0.0.
* 2.0.1
** Changed responseCode to errorHandlerResponseCode in ControllerEnhancer.groovy, so its not so generic.
* 2.0.0
** Removed autowired Grails Application from command object artifacts. This is a minor breaking change, but it is a good
idea as it will cut down on unnecessary injection, which will reduce memory used for the command object.
** Added new built-in constraints for command/domain objects:
*** notMatches - opposite of matches.
*** blackListAnd - a black list of regexes, combined with AND.
*** blackListOR - a black list of regexes, combined with OR.
*** whiteListAnd - a white list of regexes, combined with AND.
*** whiteListOR - a white list of regexes, combined with OR
* 1.0.4
** Updating the plugin to include the cascade plugin, as it works well with this plugin.
** Adding GDSL if you decide to use the global transform and not explicitly have Validateable.
** Updating the controller enhancer so that you have a choice of respond or render to deal with conflicts with gson views.
** Making the GrailsApplication from the trait injector transient to play nice with the cascade plugin.
* 1.0.3
** This release, fixes a typo issue that I'm not sure how I didn't catch, because in a different environment, the code didn't run. I also added a Global AST going toward more convention over configuration, just need to figure out GDSL to round that out(next release).
* 1.0.2
** Adding an appropriate 409 response code that can be overridden with a config change.
* 1.0.1
** Fixing issues:
*** https://github.com/virtualdogbert/command/issues/2[Improvement use respond instead of as JSON]
*** https://github.com/virtualdogbert/command/issues/1[create-command block built in grails create-command]
*** James Kleeh contributed some documentation changes.
* 1.0
** Initial Release including the ErrorsHandler annotation.
